import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowRight, Mail } from 'lucide-react';

function Header() {
  return (
    <header className="fixed top-0 left-0 w-full z-40 px-4 py-[0.85rem] md:px-7 md:py-4 flex items-center justify-between bg-gradient-to-b from-[#06111f] to-transparent">
      <div className="font-anton uppercase text-[clamp(0.92rem,1.5vw,1.25rem)] tracking-[0.08em] text-powder">
        Treeline Supply
      </div>
      
      <nav className="hidden md:flex items-center gap-6 bg-ice-900/60 backdrop-blur-md px-6 py-2 rounded-full text-xs font-mono uppercase tracking-wider border border-white/5">
        <a href="#features" className="hover:text-signal transition-colors">Features</a>
        <a href="#lookbook" className="hover:text-signal transition-colors">Lookbook</a>
        <a href="#api" className="hover:text-signal transition-colors">API Specs</a>
      </nav>

      <div className="px-3 py-1.5 md:px-4 md:py-2 text-[10px] md:text-xs uppercase font-mono tracking-wider border border-gear/30 bg-gear/10 text-gear rounded-full">
        v2.4 Engine Live
      </div>
    </header>
  );
}

function HeroSection() {
  const sectionRef = useRef<HTMLDivElement>(null);
  const [progress, setProgress] = useState(0);

  useEffect(() => {
    const handleScroll = () => {
      if (!sectionRef.current) return;
      const start = sectionRef.current.offsetTop;
      const range = sectionRef.current.offsetHeight - window.innerHeight;
      const currentScroll = window.scrollY - start;
      const p = Math.max(0, Math.min(1, currentScroll / range));
      setProgress(p);
    };

    window.addEventListener('scroll', handleScroll, { passive: true });
    handleScroll();
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  // Using a visual generated by CSS based on scroll progress instead of 203 missing JPGs.
  const visualScale = 1 + progress * 0.5;
  const gridOpacity = Math.max(0.2, 1 - progress * 0.8);
  const zOffset = progress * 100;

  return (
    <section ref={sectionRef} className="h-[520vh] relative">
      <div className="sticky top-0 h-screen w-full overflow-hidden bg-[#050d16] flex flex-col justify-between">
        
        {/* Dynamic Abstract Tech Background */}
        <div className="absolute inset-0 z-0 pointer-events-none flex items-center justify-center overflow-hidden">
          <div 
            className="absolute w-[200vw] h-[200vh] border-[1px] border-signal/10 rounded-full mix-blend-screen"
            style={{ 
              transform: `scale(${visualScale}) translateZ(${zOffset}px)`,
              opacity: gridOpacity,
              boxShadow: 'inset 0 0 100px rgba(152, 245, 255, 0.1)'
            }}
          />
          <div 
            className="absolute w-[100vw] h-[100vh] border-[1px] border-gear/10 rounded-full mix-blend-screen"
            style={{ 
              transform: `scale(${visualScale * 1.5}) rotate(${progress * 90}deg)`,
              opacity: gridOpacity * 1.5,
            }}
          />
          {/* Subtle Grid Floor */}
          <div 
            className="absolute bottom-0 w-full h-[50vh] bg-dotted-tech bg-[size:24px_24px]"
            style={{
               transform: `perspective(1000px) rotateX(80deg) translateY(${progress * 500}px)`,
               opacity: 0.3
            }}
          />
        </div>

        {/* Text Overlay */}
        <div className="relative z-10 w-full max-w-[min(1380px,100%)] mx-auto px-[clamp(1rem,3vw,2.25rem)] pt-[25vh]">
          <h1 className="font-anton uppercase text-[clamp(3rem,7.8vw,6.6rem)] leading-[1.06] max-w-[12ch] text-powder drop-shadow-2xl">
            Automated Data, <br/>
            Zero Friction
          </h1>
          <p className="mt-6 font-mono text-ice-200 max-w-md text-sm md:text-base leading-relaxed">
            Extract features, BOMs, and dimensions from engineering drawings with our AI engine. Built for fast RFQ turnarounds.
          </p>
        </div>

        {/* Bottom Elements */}
        <div className="relative z-10 w-full max-w-[min(1380px,100%)] mx-auto px-[clamp(1rem,3vw,2.25rem)] pb-8 flex justify-between items-end">
          <div className="flex items-center gap-3 text-xs uppercase font-mono tracking-widest text-ice-200">
            <ArrowDown className="w-5 h-5 animate-bounce text-signal" />
            <span>Scroll</span>
          </div>
        </div>

        {/* Right side progress rail */}
        <div className="absolute right-4 top-1/4 bottom-1/4 w-[2px] bg-white/5 rounded-full overflow-hidden">
          <div 
            className="w-full bg-gradient-to-b from-signal to-gear origin-top"
            style={{ transform: `scaleY(${progress})`, height: '100%' }}
          />
        </div>
        
        {/* Overlay Gradients */}
        <div className="absolute inset-0 pointer-events-none bg-gradient-to-b from-ice-950/40 via-transparent to-ice-950/80 z-0" />
      </div>
    </section>
  );
}

const FEATURE_ITEMS = [
  {
    name: 'Geometry Parser v2',
    type: 'Extraction',
    detail: 'Identifies holes, bends, and tolerances directly from PDF blueprints with 99.8% accuracy.',
    stat: '< 2.4s per drawing',
  },
  {
    name: 'BOM Compiler',
    type: 'Data',
    detail: 'Automatically generates hierarchical bill of materials from assembly drawings.',
    stat: 'XLSX / CSV Export',
  },
  {
    name: 'Auto-Costing Engine',
    type: 'Pricing',
    detail: 'Maps extracted geometry to your machine shop rates to generate instant quotes.',
    stat: 'API Ready',
  },
  {
    name: 'Material Detector',
    type: 'Analysis',
    detail: 'Cross-references title blocks and notes to isolate material requirements and finish specs.',
    stat: '150+ Alloys Mapped',
  },
];

function FeatureJumpSection() {
  const sectionRef = useRef<HTMLDivElement>(null);
  const [progress, setProgress] = useState(0);

  useEffect(() => {
    const handleScroll = () => {
      if (!sectionRef.current) return;
      const start = sectionRef.current.offsetTop;
      const range = sectionRef.current.offsetHeight - window.innerHeight;
      const currentScroll = window.scrollY - start;
      const p = Math.max(0, Math.min(1, currentScroll / range));
      setProgress(p);
    };

    window.addEventListener('scroll', handleScroll, { passive: true });
    handleScroll();
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const activeIndex = Math.min(
    FEATURE_ITEMS.length - 1,
    Math.floor(progress * FEATURE_ITEMS.length)
  );

  return (
    <section ref={sectionRef} className="h-[480vh] relative bg-ice-950" id="features">
      <div className="sticky top-0 h-screen w-full overflow-hidden flex flex-col justify-center">
        
        {/* Dynamic Tech BG for Section 2 */}
        <div className="absolute inset-0 pointer-events-none opacity-30">
          <div 
            className="w-full h-full bg-ice-900"
            style={{ 
               backgroundImage: 'linear-gradient(rgba(152, 245, 255, 0.05) 1px, transparent 1px), linear-gradient(90deg, rgba(152, 245, 255, 0.05) 1px, transparent 1px)',
               backgroundSize: '40px 40px',
               transform: `translateY(${-(progress * 100)}px)`
            }}
          />
        </div>

        <div className="relative z-10 w-full max-w-[min(1380px,100%)] mx-auto px-[clamp(1rem,3vw,2.25rem)] grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
          
          {/* Left Copy */}
          <div>
            <h2 className="font-anton uppercase text-[clamp(2.5rem,5vw,4.5rem)] leading-[1.06] text-powder mb-6">
              Review the Pipeline <br/>
              <span className="text-ice-800" style={{WebkitTextStroke: '1px #98f5ff'}}>Data that</span><br/>
              builds quotes
            </h2>
            <p className="font-mono text-ice-200 max-w-sm text-sm leading-relaxed">
              The extraction sequence acts as a digital engineer: each step brings one layer of the drawing into focus before processing.
            </p>
          </div>

          {/* Right Cards Sliding In */}
          <div className="relative h-[24rem] w-full max-w-[min(24rem,calc(100vw-2rem))] ml-auto perspective-1000">
            {FEATURE_ITEMS.map((item, idx) => {
              const isActive = idx === activeIndex;
              const isPast = idx < activeIndex;
              
              let transform = 'translateX(120%) rotateY(-20deg)';
              let opacity = 0;
              
              if (isActive) {
                transform = 'translateX(0) rotateY(0)';
                opacity = 1;
              } else if (isPast) {
                transform = 'translateX(-120%) rotateY(20deg) scale(0.9)';
                opacity = 0;
              }

              return (
                <div
                  key={item.name}
                  className="absolute inset-0 bg-[#0a1628]/80 backdrop-blur-xl border border-white/10 rounded-xl p-8 flex flex-col justify-between shadow-2xl transition-all duration-500 ease-[cubic-bezier(0.2,0.8,0.2,1)]"
                  style={{ transform, opacity, visibility: opacity > 0 ? 'visible' : 'hidden' }}
                >
                  <div>
                    <div className="inline-block px-3 py-1 bg-gear/10 border border-gear/30 text-gear rounded-full text-xs font-mono uppercase mb-4">
                      0{idx + 1} // {item.type}
                    </div>
                    <h3 className="font-anton uppercase text-3xl mb-4 text-powder">{item.name}</h3>
                    <p className="font-mono text-sm text-ice-200 leading-relaxed">
                      {item.detail}
                    </p>
                  </div>
                  <div className="pt-6 border-t border-white/10 mt-6 flex justify-between items-center">
                    <span className="font-mono text-xs uppercase text-signal">Metric</span>
                    <span className="font-mono text-sm font-medium text-powder">{item.stat}</span>
                  </div>
                </div>
              );
            })}
          </div>

        </div>

        {/* Bottom Progress */}
        <div className="absolute bottom-0 left-0 w-full h-1 bg-white/5">
          <div 
            className="h-full bg-gear origin-left transition-transform duration-100 ease-linear"
            style={{ transform: `scaleX(${progress})` }}
          />
        </div>
      </div>
    </section>
  );
}

const LOOKBOOK_ITEMS = [
  {
    image: '/assets/product-cards/geometric_feature_analysis.png',
    eyebrow: 'AI Parser',
    title: 'Feature Analysis',
    copy: 'A deep learning model identifying critical geometric features across varying blueprint standards.',
  },
  {
    image: '/assets/product-cards/bom_extraction.png',
    eyebrow: 'Data Tables',
    title: 'BOM Extraction',
    copy: 'Extracting clean, hierarchical Bill of Materials data directly from complex PDF assemblies.',
  },
  {
    image: '/assets/product-cards/automated_costing.png',
    eyebrow: 'Routing',
    title: 'Automated Costing',
    copy: 'Generating immediate, accurate cost estimates based on machine run-time and material volume.',
  },
];

function LookbookSection() {
  return (
    <section className="py-24 md:py-32 relative" id="lookbook">
      {/* Texture applied via global CSS, this section is transparent so it shows through */}
      <div className="w-full max-w-[min(1380px,100%)] mx-auto px-[clamp(1rem,3vw,2.25rem)]">
        
        <h2 className="font-anton uppercase text-[clamp(2.2rem,6vw,4.8rem)] leading-[1.06] text-powder max-w-[22ch] mb-16">
          System lookbook <br/>
          <span className="text-ice-200/50">Processing logic, <br/>visualized</span>
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {LOOKBOOK_ITEMS.map((item, idx) => (
            <div key={idx} className="relative group overflow-hidden rounded-xl border border-white/5 min-h-[30rem] bg-ice-900">
              <img 
                src={item.image} 
                alt={item.title} 
                className="absolute inset-0 w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
              />
              {/* Very translucent thin caption bar at bottom */}
              <div className="absolute bottom-0 left-0 right-0 p-[0.4rem_0.55rem] bg-[#050c16]/40 backdrop-blur-md border-t border-white/5 flex items-center gap-3">
                <span className="font-mono text-[10px] uppercase text-signal shrink-0">{item.eyebrow}</span>
                <span className="font-anton uppercase tracking-wide text-powder text-sm truncate">{item.title}</span>
              </div>
            </div>
          ))}
        </div>

      </div>
    </section>
  );
}

function CTASection() {
  return (
    <section className="py-24 md:py-40 relative border-t border-white/5">
      <div className="w-full max-w-[min(1380px,100%)] mx-auto px-[clamp(1rem,3vw,2.25rem)]">
        
        <div className="bg-[#0a1628]/40 backdrop-blur-xl border border-white/10 rounded-2xl p-10 md:p-20 relative overflow-hidden">
          {/* Decorative glow */}
          <div className="absolute top-0 right-0 w-[40rem] h-[40rem] bg-signal/5 rounded-full blur-[100px] -translate-y-1/2 translate-x-1/3 pointer-events-none" />
          
          <div className="relative z-10 max-w-2xl">
            <h2 className="font-anton uppercase text-[clamp(2.2rem,6vw,4.9rem)] leading-[1.06] text-powder mb-10 max-w-[24ch]">
              Ready for the next RFQ <br/>
              <span className="text-gear">Automate quoting. <br/>Start with the drawing.</span>
            </h2>

            <div className="flex flex-col sm:flex-row gap-4">
              <button className="flex items-center justify-center gap-3 bg-gear text-ice-950 font-mono font-bold uppercase text-xs tracking-wider px-8 py-4 rounded-full hover:bg-white transition-colors">
                <span>Start API Trial</span>
                <ArrowRight className="w-4 h-4" />
              </button>
              
              <button className="flex items-center justify-center gap-3 bg-white/5 text-powder border border-white/20 font-mono font-medium uppercase text-xs tracking-wider px-8 py-4 rounded-full hover:bg-white/10 transition-colors">
                <Mail className="w-4 h-4" />
                <span>Contact Engineering</span>
              </button>
            </div>
          </div>
        </div>

        {/* Footer Links */}
        <div className="mt-20 flex flex-wrap gap-4 text-xs font-mono uppercase tracking-widest border-t border-white/10 pt-8 text-ice-200">
          <a href="#" className="px-4 py-2 border border-white/10 rounded-full hover:text-signal transition-colors">Mail</a>
          <a href="#lookbook" className="px-4 py-2 border border-white/10 rounded-full hover:text-signal transition-colors">Lookbook</a>
          <a href="#features" className="px-4 py-2 border border-white/10 rounded-full hover:text-signal transition-colors">Features</a>
          <div className="ml-auto px-4 py-2 text-white/30">© {new Date().getFullYear()} Treeline Supply / Data Division</div>
        </div>
        
      </div>
    </section>
  );
}

function App() {
  return (
    <div className="bg-ice-950 min-h-screen relative selection:bg-signal selection:text-ice-950">
      <Header />
      <main>
        <HeroSection />
        <FeatureJumpSection />
        <LookbookSection />
        <CTASection />
      </main>
    </div>
  );
}

export default App;
